apiVersion: apps/v1
kind: Deployment
metadata:
  name: quelpoke
  namespace: robin
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/robin: quelpoke
  template:
    metadata:
      labels:
        app.kubernetes.io/robin: quelpoke
    spec:
      containers:
      - name: quelpoke
        image: robin/quelpoke:1724838657
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 64Mi