apiVersion: v1
kind: Service
metadata:
  name: service-robin
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "service-robin"}}}'
spec:
  selector:
    app.kubernetes.io/robin: quelpoke-robin
  ports:
    - name: service-port-8080
      protocol: TCP
      port: 80
      targetPort: 8080