name: Quelpoke build and push

on:
  push:
    branches: [ "docker-push" ]
  pull_request:
    branches: [ "docker-push" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Connect to GCP
      run: docker login -u json_key_base64 -p '${{ secrets.GOOGLE_CREDENTIALS }}' europe-west9-docker.pkg.dev
    - name: Tag image
      run: tag quelpoke:$(date +%s) europe-west9-docker.pkg.dev/infal-devops-sysops/student-robin/monapp 
    - name: push to gcp
      run: docker push europe-west9-docker.pkg.dev/infal-devops-sysops/student-robin/monapp
