name: Quelpoke build and push

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set env
      run: echo "DATE=$(date +%s)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag quelpoke:${{ env.DATE }}
    - uses: wemake-services/docker-image-size-limit@master
      with:
        image: "quelpoke"
        size: "5MB"
    - name: Docker login
      uses: docker/login-action@v3
      with:
        registry: europe-west9-docker.pkg.dev
        username: _json_key_base64
        password: ${{ secrets.GOOGLE_CREDENTIALS }}
    - name: Tag image
      run: docker tag quelpoke:${{ env.DATE }} europe-west9-docker.pkg.dev/infal-devops-sysops/student-robin/monapp 
    - name: push to gcp
      run: docker push europe-west9-docker.pkg.dev/infal-devops-sysops/student-robin/monapp
