name: Quelpoke build and push

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set env
      run: echo "DOCKER_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag quelpoke:${{ env.DOCKER_TAG }}
    - name: Test Size Image
      uses: wemake-services/docker-image-size-limit@master
      with:
        image: "quelpoke:${{ env.DOCKER_TAG }}"
        size: "20MB"
    - name: Docker login
      uses: docker/login-action@v3
      with:
        registry: europe-west9-docker.pkg.dev
        username: _json_key_base64
        password: ${{ secrets.GOOGLE_CREDENTIALS }}
    - name: Tag image
      run: docker tag quelpoke:${{ env.DOCKER_TAG }} europe-west9-docker.pkg.dev/infal-devops-sysops/student-robin/quelpoke:${{ env.DOCKER_TAG }} 
    - name: push to gcp
      run: docker push europe-west9-docker.pkg.dev/infal-devops-sysops/student-robin/quelpoke:${{ env.DOCKER_TAG }}

    - name: Checkout code
      uses: actions/checkout@v3
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GKE_SERVICE_ACCOUNT_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Use gcloud CLI
      run: |
        gcloud components install gke-gcloud-auth-plugin
      
    - name: Authenticate to GKE
      run: |
        gcloud container clusters get-credentials lab-cluster --zone europe-west9 --project infal-devops-sysops
    - name: Create Namespace
      run: |
        export DOCKER_TAG=${{ env.DOCKER_TAG }}
        cat automate.yaml | envsubst | kubectl apply -f -
