name: Quelpoke build and push

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Docker login
      uses: docker/login-action@v3
      with:
        registry: europe-west9-docker.pkg.dev
        username: _json_key_base64
        password: ${{ secrets.GOOGLE_CREDENTIALS }}
    - name: Tag image
      run: docker tag quelpoke europe-west9-docker.pkg.dev/infal-devops-sysops/student-robin/monapp 
    - name: push to gcp
      run: docker push europe-west9-docker.pkg.dev/infal-devops-sysops/student-robin/monapp
